// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVV1B_aflWrtY3nDm0YU6u3ZVojuREYc',
    appId: '1:98774579731:web:095f3c29b8a74e018a9de6',
    messagingSenderId: '98774579731',
    projectId: 'fooddeliverytute-639fe',
    authDomain: 'fooddeliverytute-639fe.firebaseapp.com',
    storageBucket: 'fooddeliverytute-639fe.firebasestorage.app',
    measurementId: 'G-K2JHKXLKDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4iWHtf6UiGhdxIYnDY_PqQFzRNKTKzE',
    appId: '1:98774579731:android:5e699e0a381d36f98a9de6',
    messagingSenderId: '98774579731',
    projectId: 'fooddeliverytute-639fe',
    storageBucket: 'fooddeliverytute-639fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSQ094mdnIkWM11i9TDfJeH5O6RDolj4',
    appId: '1:98774579731:ios:b18339d51af8419a8a9de6',
    messagingSenderId: '98774579731',
    projectId: 'fooddeliverytute-639fe',
    storageBucket: 'fooddeliverytute-639fe.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvSQ094mdnIkWM11i9TDfJeH5O6RDolj4',
    appId: '1:98774579731:ios:b18339d51af8419a8a9de6',
    messagingSenderId: '98774579731',
    projectId: 'fooddeliverytute-639fe',
    storageBucket: 'fooddeliverytute-639fe.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFVV1B_aflWrtY3nDm0YU6u3ZVojuREYc',
    appId: '1:98774579731:web:77ffdf3231a8df058a9de6',
    messagingSenderId: '98774579731',
    projectId: 'fooddeliverytute-639fe',
    authDomain: 'fooddeliverytute-639fe.firebaseapp.com',
    storageBucket: 'fooddeliverytute-639fe.firebasestorage.app',
    measurementId: 'G-327CRWVNJX',
  );

}